### ISSUE TITLE
Use NodeJS linux binaries instead of compiling from source

### ISSUE THREAD

**Issue by GeorgeBekh** [judge0/api-base#4]
It'll be quicker

**Comment by hermanzdosilovic** [comment]
I agree, that will be faster to build.

Can you create a pull request with this change?

**Comment by GeorgeBekh** [comment]
Ok but we need to fix the dockerfile first :) because right now `docker build` fails 
https://github.com/judge0/api-base/pull/2

**Comment by GeorgeBekh** [comment]
Solved in https://github.com/judge0/api-base/pull/2
