### ISSUE TITLE
Make image judge0/buildpack-deps open source

### ISSUE THREAD

**Issue by GeorgeBekh** [judge0/api-base#6]
Right now it's not possible to see the Dockerfile from which the image was built

**Comment by hermanzdosilovic** [comment]
Image `judge0/buildpack-deps` is just a new name for `buildpack-deps` official image on Docker Hub.

On Docker Hub you have, for example, official `buildpack-deps:jessie` image that gets updated once in a while (I don't know the frequency of the update). I pulled this image once on my PC and pushed it under different name on my own registry. Judge0 API Base uses [`judge0/buildpack-deps:jessie-2017-03-21`](https://github.com/judge0/api-base/blob/master/Dockerfile#L1) image. This means that I am using `buildpack-deps:jessie` image that was last time updated on March 21, 2017. I am doing this to preserve build cache when I need to add a new language, build some other Judge0 API release, or just to test something.

**Comment by GeorgeBekh** [comment]
Ok :+1:
